(function(){'use strict';/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e=this||self;function g(){const a=h;return a&&a.visibilityState==="visible"}function k(){const a=l;return a&&a.innerWidth>0&&a.innerHeight>0}function n(a){const b=a.g&&a.i&&a.j;if(a.h===b)return!1;a.h=b;return!0}function p(a){if(n(a))for(const b of a.l)b(a.h)}function q(a){var b=r||(r=new t);a(b.h);b.l.add(a)}
var t=class{constructor(){this.l=new Set;this.i=g();this.j=k();this.h=this.g=!1;var a=e.oneAfmaInstance;this.g=a?a.visibilityState:!0;n(this);a=window.AFMA_Communicator;a==null||a.addEventListener("onshow",()=>{this.g=!0;p(this)});a==null||a.addEventListener("onhide",()=>{this.g=!1;p(this)});let b;(b=h)==null||b.addEventListener("visibilitychange",()=>{this.i=g();p(this)});let d;(d=l)==null||d.addEventListener("resize",()=>{this.j=k();p(this)})}},h=document,l=window;let r;function u(a){a.h=4;a.g&&a.setData(43,Date.now()-window.mys.pingback.getBaseTime())}var v=class{constructor(){this.g=!(!window.mys||!window.mys.pingback);this.h=0}setAttribute(a,b){this.g&&window.mys.pingback.setAttribute(a,b)}setData(a,b){this.g&&window.mys.pingback.setData(a,b,this.h)}send(a){this.g&&window.mys.pingback.send(a)}};var w,x;a:{for(var B=["CLOSURE_FLAGS"],C=e,D=0;D<B.length;D++)if(C=C[B[D]],C==null){x=null;break a}x=C}var E=x&&x[610401301];w=E!=null?E:!1;var F;const G=e.navigator;F=G?G.userAgentData||null:null;function H(a){return w?F?F.brands.some(({brand:b})=>b&&b.indexOf(a)!=-1):!1:!1}function I(a){var b;a:{if(b=e.navigator)if(b=b.userAgent)break a;b=""}return b.indexOf(a)!=-1};function J(){return w?!!F&&F.brands.length>0:!1}function L(){return J()?H("Chromium"):(I("Chrome")||I("CriOS"))&&!(J()?0:I("Edge"))||I("Silk")};function M(a,b){var d;if((a.g.includes(b)||a.i.includes(b))&&((d=window.performance)==null?0:d.getEntries)&&window.PerformanceNavigationTiming&&window.PerformanceResourceTiming){d=a.g.includes(b)?["script"]:[];var c=window.performance.getEntries(),f=0,y=0,z=0,A=0;for(const m of c)if(!m.name.includes("pagead2.googlesyndication.com/pagead/gen_204?id=mys"))if(m instanceof window.PerformanceNavigationTiming)f+=m.transferSize||0;else if(m instanceof window.PerformanceResourceTiming){c=m.initiatorType;
const K=m.transferSize||0;if(d.length===0||d.includes(c))z++,y+=K===0?1:0,A+=K}a.g.includes(b)?(a.pingback.setData(16,f),a.pingback.setData(17,A),a.pingback.setData(18,z),a.pingback.setData(19,y)):a.i.includes(b)&&(a.pingback.setData(20,A),a.pingback.setData(21,z),a.pingback.setData(22,y))}a.pingback.setData(b,window.performance.now());a.pingback.send()}function N(a,b){a.h[b]=window.performance.now()}
function O(a,b){a.h.hasOwnProperty(b)&&(a.pingback.setData(b,window.performance.now()-a.h[b]),b===13&&(a.pingback.setData(30,`${window.innerWidth}x${window.innerHeight}`),a.pingback.setData(25,`${a.body.clientWidth}x${a.body.clientHeight}`)),a.pingback.send())}
var Q=class{constructor(){this.body=P;this.pingback=new v;this.h={};this.j={overallStart:()=>void M(this,3),overallReady:()=>void M(this,4),overallQuiet:()=>void M(this,5),overallError:()=>void M(this,6),assembleStart:()=>void N(this,7),assembleReady:()=>void O(this,7),decorateStart:()=>void N(this,8),decorateReady:()=>void O(this,8),fontStart:()=>void N(this,9),fontReady:()=>void O(this,9),spanStart:()=>void N(this,10),spanReady:()=>void O(this,10),prepareStart:()=>void N(this,11),prepareReady:()=>
void O(this,11),bindingStart:()=>void N(this,12),bindingReady:()=>void O(this,12),browserStart:()=>void N(this,13),browserStartEnd:()=>void O(this,13),browserReady:()=>void N(this,14),browserReadyEnd:()=>void O(this,14),browserQuiet:()=>void N(this,15),browserQuietEnd:()=>void O(this,15)};this.g=[23];this.i=[24];u(this.pingback)}};const P=document.getElementById("mys-content");
(function(){var a=new Q;let b;if((b=window.mys)!=null&&b.pingback){window.addEventListener("error",c=>{a.pingback.setData(1,c.message);a.pingback.setData(95,c.filename);a.pingback.send()});a.body.addEventListener("customError",c=>{let f="custom_error: ";c.detail&&(f+=c.detail.message);a.pingback.setData(2,f);a.pingback.send()});window.addEventListener("click",c=>{const f=Date.now()-window.mys.pingback.getBaseTime();a.pingback.setData(47,`${c.clientX}x${c.clientY}@${f}`);a.pingback.send()},!0);var d;
if((d=window.performance)!=null&&d.now){window.addEventListener("DOMContentLoaded",()=>void M(a,23));window.addEventListener("load",()=>{M(a,24);setTimeout(()=>{var c;(c=window.performance)!=null&&c.getEntriesByType&&(c=performance.getEntriesByType("navigation")[0])&&(a.pingback.setData(50,c.fetchStart),a.pingback.setData(51,c.domainLookupStart),a.pingback.setData(52,c.domainLookupEnd),a.pingback.setData(53,c.connectStart),a.pingback.setData(54,c.connectEnd),a.pingback.setData(55,c.secureConnectionStart),
a.pingback.setData(56,c.requestStart),a.pingback.setData(57,c.responseStart),a.pingback.setData(58,c.responseEnd),a.pingback.setData(59,c.domInteractive),a.pingback.setData(60,c.domContentLoadedEventStart),a.pingback.setData(61,c.domContentLoadedEventEnd),a.pingback.setData(62,c.domComplete),a.pingback.setData(63,c.loadEventStart),a.pingback.setData(64,c.loadEventEnd),a.pingback.send())},0)});q(c=>{c?a.pingback.setData(75,window.performance.now()):a.pingback.setData(76,window.performance.now());a.pingback.send()});
for(const [c,f]of Object.entries(a.j))a.body.addEventListener(c,f)}}})();!I("Android")||L();L();I("Safari")&&(L()||(J()?0:I("Coast"))||(J()?0:I("Opera"))||(J()?0:I("Edge"))||(J()?H("Microsoft Edge"):I("Edg/"))||J()&&H("Opera"));}).call(this);
